#+Title: HWK 11
#+Subtitle: Due Tuesday December 8th, 6p.m.
#+Author: Jeffery Zucker
#+Options: num:nil
#+Description: Homework 11
#+SETUPFILE: ./org-html-themes/setup/theme-readtheorg-local.setup

* (1)
:PROPERTIES:
:CUSTOM_ID: (1)
:END:

 Page 14-3, exercises 3, 4 and 5.

* (2)
:PROPERTIES:
:CUSTOM_ID: (2)
:END:

Page 13-2: Prove exercise 2 (i.e., for any total computable unary function $f$.)

* Hints

These brief hints were mentioned during tutorial.

** (1)

For exercise 3, take note of the binary /PR/ function
from exercise 2, which you may make use of.

For exercises 4 and 5, you should either
- provide an algorithm to compute the relation/function, or
- set up a contradiction by assuming they are computable.
Take note that these questions are part of the section on
Rice's theorem, which involves the relation ~~~.
It might be useful to find a contradiction with Rice's theorem here.

** (2)

Take note of the proof for example 1 here.

This question is slightly more general;
instead of just $φₑ(x) = e$, we want $φₑ(x) = f(e)$.
So example 1 can be thought of as the special case where $f$ is
the identity function.

* Bonus questions
:PROPERTIES:
:CUSTOM_ID: Bonus-questions
:END:

** Bonus question 5
:PROPERTIES:
:CUSTOM_ID: Bonus-question-5
:END:

Can we /strengthen/ Rice's Theorem (Theorem 14.4) to the statement:
#+begin_quote
“The only /semi-computable/ index sets are $ℕ$ and $∅$”? 
#+end_quote
I.e., are there no semi-computable index sets other than $ℕ$ and $∅$?
Either prove this or give a counter-example.

** Bonus question 6
:PROPERTIES:
:CUSTOM_ID: Bonus-question-6
:END:

Page 14-3, exercise 2.
